export interface Interest {
  name: string;
  e_d: number;   // Exploration (1) ↔ Depth (10)
  i_c: number;   // Individual (1) ↔ Collective (10)
  a_c: number;   // Abstract (1) ↔ Concrete (10)
  examples: string;
  category: string;
}

export const INTERESTS: Interest[] = [
  // Art
  { name: 'Primary Color Modernism',       e_d: 4, i_c: 3, a_c: 8, examples: 'Matisse',                              category: 'Art' },
  { name: 'Geometric Systems Art',          e_d: 5, i_c: 2, a_c: 4, examples: 'Sol LeWitt',                           category: 'Art' },
  { name: 'Impressionist Light Technique',  e_d: 3, i_c: 2, a_c: 6, examples: 'Monet, Seurat',                        category: 'Art' },
  { name: 'Street Art Energy',              e_d: 5, i_c: 8, a_c: 8, examples: 'Basquiat',                             category: 'Art' },
  { name: 'Indian Folk Visual Motifs',      e_d: 3, i_c: 6, a_c: 8, examples: 'Pichwai, Kullu',                       category: 'Art' },
  { name: 'Hand-Painted Signage Style',     e_d: 3, i_c: 7, a_c: 9, examples: 'Indian truck art',                     category: 'Art' },
  // Comedy
  { name: 'Stand-Up Appreciation',          e_d: 8, i_c: 6, a_c: 4, examples: 'Mitch Hedberg',                        category: 'Comedy' },
  { name: 'Sketch Comedy Love',             e_d: 7, i_c: 7, a_c: 5, examples: 'SNL-style sketches',                   category: 'Comedy' },
  { name: 'Wordplay Humor',                 e_d: 7, i_c: 6, a_c: 4, examples: 'Dry one-liners',                       category: 'Comedy' },
  // Cooking
  { name: 'Food Science Curiosity',         e_d: 7, i_c: 2, a_c: 4, examples: 'Reading about emulsions',              category: 'Cooking' },
  { name: 'Fermentation Projects',          e_d: 8, i_c: 3, a_c: 9, examples: 'Kimchi, sourdough',                    category: 'Cooking' },
  { name: 'Canning and Preservation',       e_d: 7, i_c: 3, a_c: 9, examples: 'Seasonal storage',                    category: 'Cooking' },
  { name: 'Knife Technique',                e_d: 7, i_c: 3, a_c: 9, examples: 'Prep discipline',                      category: 'Cooking' },
  { name: 'Hosting Meals',                  e_d: 7, i_c: 8, a_c: 9, examples: 'Dinner gatherings',                    category: 'Cooking' },
  { name: 'Home Gardening',                 e_d: 6, i_c: 3, a_c: 10, examples: 'Growing herbs',                       category: 'Cooking' },
  // Crafts
  { name: 'Drawing Practice',               e_d: 6, i_c: 2, a_c: 8, examples: 'Sketching',                            category: 'Crafts' },
  { name: 'Comic Book Fandom',              e_d: 8, i_c: 6, a_c: 4, examples: 'Graphic novels',                       category: 'Crafts' },
  // Emotional Health
  { name: 'Relationship Psychology',        e_d: 7, i_c: 6, a_c: 5, examples: 'Esther Perel',                         category: 'Emotional Health' },
  { name: 'Deep One-on-One Conversations',  e_d: 8, i_c: 8, a_c: 7, examples: 'Long talks',                           category: 'Emotional Health' },
  { name: 'Self-Reflection Practice',       e_d: 8, i_c: 2, a_c: 6, examples: 'Emotional processing',                 category: 'Emotional Health' },
  // Fashion
  { name: 'Workwear Styling',               e_d: 6, i_c: 5, a_c: 8, examples: 'Utility silhouettes',                  category: 'Fashion' },
  { name: 'Androgynous Silhouettes',        e_d: 6, i_c: 6, a_c: 7, examples: 'Neutral tailoring',                    category: 'Fashion' },
  { name: 'Retrofuturist Design',           e_d: 5, i_c: 6, a_c: 7, examples: 'Star Wars influence',                  category: 'Fashion' },
  { name: 'Japanese Contemporary Fashion',  e_d: 4, i_c: 6, a_c: 7, examples: 'Modern Japanese workwear',             category: 'Fashion' },
  // Fitness
  { name: 'HIIT Training',                  e_d: 7, i_c: 3, a_c: 9, examples: 'High intensity workouts',              category: 'Fitness' },
  { name: 'Pilates',                         e_d: 6, i_c: 4, a_c: 8, examples: 'Core strength',                        category: 'Fitness' },
  { name: 'Meditation',                     e_d: 6, i_c: 2, a_c: 5, examples: 'Mindfulness',                          category: 'Fitness' },
  // Music — instruments & production
  { name: 'Guitar Playing',                 e_d: 8, i_c: 3, a_c: 9, examples: 'Electric and acoustic',                category: 'Music' },
  { name: 'Bass Playing',                   e_d: 7, i_c: 4, a_c: 9, examples: 'Rhythm section',                       category: 'Music' },
  { name: 'Drum Kit Playing',               e_d: 7, i_c: 6, a_c: 10, examples: 'Rock grooves',                        category: 'Music' },
  { name: 'Keys and Synth Playing',         e_d: 7, i_c: 3, a_c: 8, examples: 'Chord textures',                       category: 'Music' },
  { name: 'Violin Playing',                 e_d: 6, i_c: 5, a_c: 8, examples: 'Orchestra',                            category: 'Music' },
  { name: 'Ukulele Playing',                e_d: 6, i_c: 3, a_c: 7, examples: 'Casual sets',                          category: 'Music' },
  { name: 'Horn Playing',                   e_d: 5, i_c: 4, a_c: 8, examples: 'Band arrangements',                    category: 'Music' },
  { name: 'Ableton Production',             e_d: 7, i_c: 3, a_c: 8, examples: 'Electronic tracks',                    category: 'Music' },
  { name: 'FL Studio Production',           e_d: 6, i_c: 3, a_c: 8, examples: 'Beat making',                          category: 'Music' },
  { name: 'Songwriting',                    e_d: 6, i_c: 4, a_c: 8, examples: 'Original songs',                       category: 'Music' },
  { name: 'Live Shows',                     e_d: 7, i_c: 9, a_c: 9, examples: 'Playing gigs',                         category: 'Music' },
  { name: 'Orchestra Playing',              e_d: 6, i_c: 9, a_c: 8, examples: 'Section performance',                  category: 'Music' },
  { name: 'Choir Singing',                  e_d: 6, i_c: 9, a_c: 8, examples: 'Harmony singing',                      category: 'Music' },
  { name: 'Musical Theater Performance',    e_d: 6, i_c: 9, a_c: 8, examples: 'Stage musicals',                       category: 'Music' },
  { name: 'Annual Music Review',            e_d: 9, i_c: 5, a_c: 6, examples: 'Year-end ranking list',                category: 'Music' },
  // Music — genres
  { name: '70s Punk Rock',                  e_d: 9, i_c: 9, a_c: 8, examples: 'Ramones, The Clash',                   category: 'Music' },
  { name: '80s Hardcore Punk',              e_d: 8, i_c: 9, a_c: 8, examples: 'Bad Brains, Dead Kennedys',             category: 'Music' },
  { name: 'Ska Punk',                       e_d: 8, i_c: 8, a_c: 9, examples: 'Operation Ivy, Streetlight',           category: 'Music' },
  { name: '90s Pop Punk',                   e_d: 8, i_c: 8, a_c: 8, examples: 'Blink-182, Green Day',                 category: 'Music' },
  { name: 'Emo / Scene Era',                e_d: 7, i_c: 8, a_c: 7, examples: 'MCR, Fall Out Boy',                    category: 'Music' },
  { name: 'Post-Punk',                      e_d: 8, i_c: 8, a_c: 7, examples: 'Fugazi, Mission of Burma',             category: 'Music' },
  { name: '90s Grunge',                     e_d: 8, i_c: 7, a_c: 7, examples: 'Nirvana, Smashing Pumpkins',           category: 'Music' },
  { name: '2000s NYC Indie Rock',           e_d: 9, i_c: 8, a_c: 7, examples: 'The Strokes, LCD Soundsystem',         category: 'Music' },
  { name: 'UK Indie Rock',                  e_d: 8, i_c: 8, a_c: 6, examples: 'Arctic Monkeys, Blur',                 category: 'Music' },
  { name: 'Indie Pop',                      e_d: 8, i_c: 7, a_c: 6, examples: 'Belle and Sebastian, Phoenix',         category: 'Music' },
  { name: 'Art Rock / Experimental Indie',  e_d: 8, i_c: 6, a_c: 6, examples: 'Animal Collective, Radiohead',         category: 'Music' },
  { name: 'Classic Rock 60s–70s',           e_d: 9, i_c: 8, a_c: 6, examples: 'Beatles, Zeppelin',                   category: 'Music' },
  { name: 'Progressive Rock',               e_d: 7, i_c: 6, a_c: 5, examples: 'Yes, King Crimson',                    category: 'Music' },
  { name: 'Delta Blues',                    e_d: 7, i_c: 6, a_c: 5, examples: "Robert Johnson, Howlin' Wolf",         category: 'Music' },
  { name: 'Folk Revival',                   e_d: 7, i_c: 6, a_c: 5, examples: 'Joni Mitchell, Dylan',                 category: 'Music' },
  { name: 'Modern Indie Folk',              e_d: 7, i_c: 6, a_c: 5, examples: 'Iron & Wine, Beirut',                  category: 'Music' },
  { name: '80s Pop',                        e_d: 8, i_c: 8, a_c: 7, examples: 'Cyndi Lauper, ABBA',                   category: 'Music' },
  { name: '90s–2000s Pop',                  e_d: 8, i_c: 8, a_c: 7, examples: 'Avril Lavigne, Nelly Furtado',         category: 'Music' },
  { name: 'Golden Era Hip Hop',             e_d: 9, i_c: 9, a_c: 7, examples: 'Wu-Tang, Biggie',                      category: 'Music' },
  { name: 'Native Tongues / Conscious Rap', e_d: 9, i_c: 9, a_c: 7, examples: 'Tribe, Fugees',                        category: 'Music' },
  { name: 'Southern 2000s Rap',             e_d: 8, i_c: 8, a_c: 8, examples: 'UGK, Jeezy, Wayne',                    category: 'Music' },
  { name: 'Modern Rap',                     e_d: 7, i_c: 8, a_c: 7, examples: 'Kendrick, Vince Staples',              category: 'Music' },
  { name: 'Jazz Bebop',                     e_d: 7, i_c: 6, a_c: 4, examples: 'Charlie Parker',                       category: 'Music' },
  { name: 'Modal / Spiritual Jazz',         e_d: 7, i_c: 6, a_c: 4, examples: 'Coltrane, Pharoah Sanders',            category: 'Music' },
  { name: 'Modern UK Jazz',                 e_d: 6, i_c: 6, a_c: 5, examples: 'Shabaka, Yussef Dayes',                category: 'Music' },
  { name: 'French Touch House',             e_d: 8, i_c: 8, a_c: 8, examples: 'Daft Punk',                            category: 'Music' },
  { name: 'Chicago / Detroit House',        e_d: 7, i_c: 7, a_c: 8, examples: 'Frankie Knuckles',                     category: 'Music' },
  { name: 'UK Garage',                      e_d: 8, i_c: 8, a_c: 9, examples: 'Artful Dodger',                        category: 'Music' },
  { name: 'Progressive House 2000s',        e_d: 7, i_c: 7, a_c: 8, examples: 'Deadmau5',                             category: 'Music' },
  { name: 'Leftfield Electronic',           e_d: 7, i_c: 6, a_c: 7, examples: 'Four Tet, Floating Points',            category: 'Music' },
  { name: 'Trip Hop',                       e_d: 7, i_c: 6, a_c: 6, examples: 'Massive Attack',                       category: 'Music' },
  { name: 'Motown Soul',                    e_d: 8, i_c: 8, a_c: 7, examples: 'Stevie Wonder',                        category: 'Music' },
  { name: 'Reggaeton',                      e_d: 6, i_c: 8, a_c: 9, examples: 'Bad Bunny',                            category: 'Music' },
  { name: 'South African Dance (Amapiano)', e_d: 5, i_c: 7, a_c: 9, examples: 'Kabza De Small',                       category: 'Music' },
  { name: 'Qawwali and Ghazals',            e_d: 5, i_c: 6, a_c: 7, examples: 'Nusrat Fateh Ali Khan',                category: 'Music' },
  { name: 'Japanese City Pop',              e_d: 6, i_c: 6, a_c: 6, examples: 'Tatsuro Yamashita',                    category: 'Music' },
  { name: 'Thai Psychedelic Rock',          e_d: 5, i_c: 6, a_c: 7, examples: 'Khun Narin',                           category: 'Music' },
  { name: 'Andean Electronic Fusion',       e_d: 5, i_c: 6, a_c: 8, examples: 'Nicola Cruz',                          category: 'Music' },
  // Outdoor
  { name: 'Skiing',                         e_d: 6, i_c: 6, a_c: 10, examples: 'Mountain trips',                      category: 'Outdoor' },
  { name: 'Surfing',                         e_d: 5, i_c: 6, a_c: 10, examples: 'Ocean sessions',                      category: 'Outdoor' },
  { name: 'Hiking',                          e_d: 6, i_c: 5, a_c: 10, examples: 'Trail days',                          category: 'Outdoor' },
  { name: 'Trail Running Curiosity',        e_d: 3, i_c: 3, a_c: 9, examples: 'Beginner stage',                       category: 'Outdoor' },
  { name: 'Skateboarding Curiosity',        e_d: 2, i_c: 4, a_c: 9, examples: 'Beginner stage',                       category: 'Outdoor' },
  // Professional
  { name: 'Deep Math and AI Theory',                e_d: 9, i_c: 2, a_c: 1, examples: '',                             category: 'Professional' },
  { name: 'Understanding How Models Work',           e_d: 9, i_c: 2, a_c: 1, examples: '',                             category: 'Professional' },
  { name: 'Solving Hard Problems Alone',             e_d: 10, i_c: 1, a_c: 1, examples: '',                            category: 'Professional' },
  { name: 'Designing and Running Experiments',       e_d: 8, i_c: 3, a_c: 2, examples: '',                             category: 'Professional' },
  { name: 'Writing Technical Papers',                e_d: 8, i_c: 6, a_c: 2, examples: '',                             category: 'Professional' },
  { name: 'Explaining Complex Ideas Clearly',        e_d: 8, i_c: 7, a_c: 3, examples: '',                             category: 'Professional' },
  { name: 'Turning Theory into Real-World Tools',    e_d: 8, i_c: 6, a_c: 4, examples: '',                             category: 'Professional' },
  { name: 'Building Machine Learning Systems',       e_d: 7, i_c: 5, a_c: 2, examples: '',                             category: 'Professional' },
  { name: 'Designing System Architecture',           e_d: 7, i_c: 5, a_c: 3, examples: '',                             category: 'Professional' },
  { name: 'Building New Projects from Scratch',      e_d: 7, i_c: 4, a_c: 4, examples: '',                             category: 'Professional' },
  { name: 'Deciding AI Product Direction',           e_d: 6, i_c: 7, a_c: 5, examples: '',                             category: 'Professional' },
  { name: 'Mentoring and Growing Engineers',         e_d: 6, i_c: 8, a_c: 5, examples: '',                             category: 'Professional' },
  { name: 'Leading Technical Teams',                 e_d: 6, i_c: 9, a_c: 6, examples: '',                             category: 'Professional' },
  { name: 'Making High-Stakes Startup Decisions',    e_d: 6, i_c: 8, a_c: 6, examples: '',                             category: 'Professional' },
  { name: 'Learning New Mathematical Fields',        e_d: 5, i_c: 2, a_c: 1, examples: '',                             category: 'Professional' },
  { name: 'Exploring AI Alignment Questions',        e_d: 5, i_c: 5, a_c: 2, examples: '',                             category: 'Professional' },
  { name: 'Philosophy of Mind and Consciousness',    e_d: 4, i_c: 3, a_c: 1, examples: '',                             category: 'Professional' },
  { name: 'Global Economics and Systems',            e_d: 4, i_c: 6, a_c: 2, examples: '',                             category: 'Professional' },
  { name: 'Personal Brand Strategy',                 e_d: 3, i_c: 7, a_c: 4, examples: '',                             category: 'Professional' },
  { name: 'Visual Design for Technical Tools',       e_d: 3, i_c: 4, a_c: 6, examples: '',                             category: 'Professional' },
  { name: 'Fundraising and Investor Relations',      e_d: 3, i_c: 8, a_c: 6, examples: '',                             category: 'Professional' },
  // Puzzles
  { name: 'Logic Puzzle Games',             e_d: 8, i_c: 2, a_c: 4, examples: 'Portal, Fez',                          category: 'Puzzles' },
  { name: 'Adventure Puzzle Games',         e_d: 8, i_c: 3, a_c: 6, examples: 'Zelda',                                category: 'Puzzles' },
  // Reading
  { name: 'Magical Realism Literature',     e_d: 8, i_c: 2, a_c: 3, examples: 'Gabriel García Márquez',               category: 'Reading' },
  { name: 'Comics and Graphic Novels',      e_d: 8, i_c: 6, a_c: 4, examples: 'Graphic novels',                       category: 'Reading' },
  { name: 'Nonfiction Self-Optimization',   e_d: 7, i_c: 2, a_c: 2, examples: 'Life hacking books',                   category: 'Reading' },
  // Sports
  { name: 'Baseball Fandom',                e_d: 8, i_c: 9, a_c: 6, examples: 'Mets',                                 category: 'Sports' },
  { name: 'Hockey Fandom',                  e_d: 8, i_c: 9, a_c: 7, examples: 'Rangers',                              category: 'Sports' },
  { name: 'Basketball Fandom',              e_d: 8, i_c: 9, a_c: 7, examples: 'Knicks',                               category: 'Sports' },
  { name: 'Soccer Fandom',                  e_d: 8, i_c: 9, a_c: 7, examples: 'Liverpool FC',                         category: 'Sports' },
  // Travel
  { name: 'Cultural Immersion Travel',      e_d: 6, i_c: 7, a_c: 9, examples: 'Learning local customs',               category: 'Travel' },
  { name: 'Food-Centered Travel',           e_d: 6, i_c: 7, a_c: 9, examples: 'Traveling for cuisine',                category: 'Travel' },
  { name: 'Music Scene Travel',             e_d: 6, i_c: 8, a_c: 9, examples: 'Travel for shows',                     category: 'Travel' },
  { name: 'Nature Travel',                  e_d: 6, i_c: 5, a_c: 10, examples: 'Mountains, ocean',                    category: 'Travel' },
  // TV and Film
  { name: 'Found Family Fantasy',           e_d: 4, i_c: 8, a_c: 8, examples: 'She-Ra, Avatar, Voltron, Korra',       category: 'TV and Film' },
  { name: 'Institutional Power Drama',      e_d: 4, i_c: 7, a_c: 6, examples: 'The Wire, Godfather, Andor',           category: 'TV and Film' },
  { name: 'Moral Descent and Escalation',   e_d: 4, i_c: 7, a_c: 6, examples: 'Breaking Bad, Ozark',                  category: 'TV and Film' },
  { name: 'Puzzle-Box Narratives',          e_d: 4, i_c: 6, a_c: 5, examples: 'Memento, Prestige, Dark',              category: 'TV and Film' },
  { name: 'High-Concept Sci-Fi',            e_d: 4, i_c: 7, a_c: 7, examples: 'Interstellar, Severance, Silo',        category: 'TV and Film' },
  { name: 'Stylized Crime and Cool Dialogue',e_d: 4, i_c: 8, a_c: 6, examples: 'Pulp Fiction, Fargo, Knives Out',     category: 'TV and Film' },
  { name: 'Warm Ensemble Comedy',           e_d: 4, i_c: 9, a_c: 7, examples: 'The Office, Parks and Rec, Scrubs',   category: 'TV and Film' },
  { name: 'Earnest Growth Drama',           e_d: 4, i_c: 8, a_c: 7, examples: 'Sex Education, Friday Night Lights',  category: 'TV and Film' },
  { name: 'Whimsical Heartfelt Storytelling',e_d: 4, i_c: 8, a_c: 8, examples: 'Big Fish, Paddington, Spirited Away', category: 'TV and Film' },
  { name: 'Romantic Comedy Comfort',        e_d: 4, i_c: 8, a_c: 7, examples: 'When Harry Met Sally, Mean Girls',    category: 'TV and Film' },
  { name: 'Animated Emotional Growth',      e_d: 4, i_c: 8, a_c: 8, examples: 'Inside Out, Moana, Toy Story',         category: 'TV and Film' },
  { name: 'Smart Absurdist Comedy',         e_d: 4, i_c: 7, a_c: 6, examples: 'Futurama, Rick and Morty',            category: 'TV and Film' },
  { name: 'Prestige Indie Drama',           e_d: 4, i_c: 6, a_c: 7, examples: 'Short Term 12, Florida Project',      category: 'TV and Film' },
  { name: 'Psychological Tension',          e_d: 4, i_c: 6, a_c: 7, examples: 'Fincher films, Jordan Peele',         category: 'TV and Film' },
  // Writing
  { name: 'Short Story Writing',            e_d: 6, i_c: 2, a_c: 4, examples: 'Fiction drafts',                       category: 'Writing' },
  { name: 'Poetry Writing',                 e_d: 6, i_c: 2, a_c: 3, examples: 'Personal poems',                       category: 'Writing' },
  { name: 'Magical Realism Writing',        e_d: 6, i_c: 3, a_c: 4, examples: 'Surreal storytelling',                 category: 'Writing' },
  { name: 'Comic Creation',                 e_d: 6, i_c: 4, a_c: 7, examples: 'Panels and narrative',                 category: 'Writing' },
];

export const CATEGORY_COLORS: Record<string, string> = {
  'Art':              '#FF007A',
  'Comedy':           '#FF6B35',
  'Cooking':          '#FFD166',
  'Crafts':           '#06D6A0',
  'Emotional Health': '#C77DFF',
  'Fashion':          '#FF84E8',
  'Fitness':          '#52EFAA',
  'Music':            '#A8FF3D',
  'Outdoor':          '#48CAE4',
  'Professional':     '#9DB4C0',
  'Puzzles':          '#FF9F1C',
  'Reading':          '#E040FB',
  'Sports':           '#4895EF',
  'Travel':           '#2EC4B6',
  'TV and Film':      '#FF6B6B',
  'Writing':          '#F7ECE1',
};
